import { useEffect } from "react";
import { getRedirectResult } from "firebase/auth";

import { auth, signInWithGooglePopup, signInWithGoogleRedirect, createUserDocumentFromAuth } from "../../utilities/firebase/firebase";

import SignUpForm from "../../components/sign-up-form/sign-up-form.component";

const SignIn = () => {
    useEffect(() => {
        async function redirect() {
            const response = await getRedirectResult(auth); //auth相当于一个bank，存着所有authentication instance info
            console.log(response);}
            redirect()}
            , []) //给一个空array means component第一次mount的时候运行里面的callback func

    const logGoogleUser = async () => {
        const response = await signInWithGooglePopup();
        console.log(response)
        //response包含accessToken generated by Firebase, for making CRUD requests
        const userDocRef = await createUserDocumentFromAuth(response.user)    
    }

    return (
        <div>
            <h1>This is a sign-in page.</h1>
            <button onClick={logGoogleUser}> Google Sign In with Popup</button>
            <button onClick={signInWithGoogleRedirect}> Google Sign In with Redirect</button>
            <SignUpForm />
        </div>
    )
}

export default SignIn;