import { signInWithGooglePopup, createUserDocumentFromAuth } from "../../utilities/firebase/firebase";

const SignIn = () => {

    const logGoogleUser = async () => {
        const response = await signInWithGooglePopup();
        //response包含accessToken generated by Firebase, for making CRUD requests
        const userDocRef = await createUserDocumentFromAuth(response.user)
    }

    return (
        <div>
            <h1>This is a sign-in page.</h1>
            <button onClick={logGoogleUser}> Google Sign In</button>
        </div>
    )
}

export default SignIn;